# Generated by Django 4.2.7 on 2023-12-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gzl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artical",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
                ("favorites_num", models.IntegerField(blank=True, null=True)),
                ("like_num", models.IntegerField(blank=True, null=True)),
                ("comment_num", models.IntegerField(blank=True, null=True)),
                ("atime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "artical",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("nid", models.IntegerField(primary_key=True, serialize=False)),
                ("ncontent", models.CharField(blank=True, max_length=255, null=True)),
                ("ntime", models.DateTimeField(blank=True, null=True)),
                ("type", models.IntegerField()),
            ],
            options={
                "db_table": "notice",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                ("picture", models.CharField(blank=True, max_length=255, null=True)),
                ("remark", models.CharField(blank=True, max_length=255, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="gzl.user",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=255, null=True)),
                ("ctime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "comment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Favorites",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="gzl.user",
                    ),
                ),
                ("ftime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "favorites",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="gzl.user",
                    ),
                ),
                ("ltime", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "like",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserGroup",
            fields=[
                (
                    "gid",
                    models.OneToOneField(
                        db_column="gid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="gzl.group",
                    ),
                ),
            ],
            options={
                "db_table": "user_group",
                "managed": False,
            },
        ),
    ]
